### ISSUE TITLE
Hot Reloading does not work for @import CSS

### ISSUE THREAD

**Issue by manavsehgal** [manavsehgal/reactspeedcoding#1]
Hot Reloading works just fine for any changes within React code (JSX). However, as we make changes
to partials or CSS imports in [/app/styles/][1] folder, these changes are not hot reloaded in the browser.
It works fine for changes within [/app/style.css][2] though.

We are trying several possible solutions to this [know issue][4]. Following have been tried and failed...

1. Using postcss-import and addDependencyTo: webpack. Not recommended approach as per the above mentioned [thread][4].
2. Chaining css-loader imports as [mentioned here][3].

[1]: https://github.com/manavsehgal/reactspeedcoding/tree/master/code/app/styles
[2]: https://github.com/manavsehgal/reactspeedcoding/blob/master/code/app/style.css
[3]: https://github.com/webpack/css-loader#importing-and-chained-loaders
[4]: https://github.com/postcss/postcss-loader/issues/8

**Comment by douglasdeodato** [comment]
hello I heard about this project on reddit, I can help out to convert and refractory your css and move on for sass or scss? will be a pleasure help with that and maybe we can apply grunt task at least for the sass files? i really sure the process to import the files will be much easier, let me know what do you think, i can really help you out.  thanks.

**Comment by manavsehgal** [comment]
@douglasdeodato many thanks for reaching out and helping. I can definitely use some more contributors in this repo :-) The strategy I am following for ReactSpeed UI is to use CSS and PostCSS to keep things simple for our readers. As you know PostCSS + Precss provide most of the Sass features like nesting, inheritance, mixins, if users want to come from Sass background. Otherwise they can use plain old CSS. Where you can help is look into the CSS which uses Sass-like features and guidance from Sassway and suggest where I can make improvements. You could also help suggesting any fixes when I add CSS lint to Webpack. Hope this interests you and makes sense. Welcome on board!

**Comment by douglasdeodato** [comment]
Thanks for your answer too, yeah will be no problem to use postcss and precss will be kinda the same :), I have be looking to the css and we can some improvements for sure, I use CSS lint in my projects and that can be very helpful too I can apply this feature, about grunt do you think we can apply on this project? I can help out with everything too. I never contribute for a project here in a github, i just worked on my ones :) , so you gonna add me in the project and I can work in a different branch ? or I do a Fork? if you don't want exlain I can try find a tutorial. Thanks.

**Comment by manavsehgal** [comment]
I have created a [wiki page](https://github.com/manavsehgal/reactspeedcoding/wiki/New-Users-Contributing) that might be helpful, how new users to GitHub can contribute.

**Comment by manavsehgal** [comment]
@douglasdeodato Now that we have a wiki, hope you don't mind if I delete our conversation from this thread as it may confuse the original issue on Hot Reloading. Don't know if GitHub allows moving comments to another issue, looks like delete is the only option. Feel free to create a new issue if you want to continue discussion.

**Comment by sorrat** [comment]
@manavsehgal First solution is actually working, but you need to include `webpack` to arguments:
```js
postcss: function(webpack) {
  return [
    postcssImport({addDependencyTo: webpack}),
    //...
  ];
},
```

PS: Thanks for book!

**Comment by manavsehgal** [comment]
@sorrat many thanks for the solution. It works! Fixed in the latest commit.
