### ISSUE TITLE
static assets

### ISSUE THREAD

**Issue by ghernagon** [manavsehgal/reactspeedcoding#14]
If I place some static files like images inside /app/public folder, how can I get access to that images inside components like <img src=../public/images/my_image.png /> ???

I have tried everything with no success

**Comment by manavsehgal** [comment]
Static files in public folder will end up in build root. So refer them using [path relative to root like so](https://github.com/manavsehgal/reactspeedcoding/blob/master/app/components/FullPageHome.jsx#L18).
